/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package LaporSatpam;
import ConnectionDB.DatabaseConn;
import java.sql.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.TableRowSorter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JFileChooser;


/**
 *
 * @author USER
 */
public class MainFrame extends javax.swing.JFrame {
    private DefaultTableModel tamu;

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        DatabaseConn.connectDB();
        
         //menampilkan data Tamu pada Tabel Data Tamu di Main Frame
        this.tamu = new DefaultTableModel();
        String[] kolom = {"Nama Tamu", "NOPOL Kendaraan", "Tujuan Tamu", "Tanggal", "Waktu Kedatangan", "Durasi (Menit)", "Status"};
        tamu.setColumnIdentifiers(kolom);
        tableDataTamu.setModel(tamu);
        // ===== KODE BARU UNTUK FITUR PENCARIAN (MULAI) =====

// 1. Membuat TableRowSorter yang akan menangani proses filter/sortir
final TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(tamu);
tableDataTamu.setRowSorter(sorter);

// 2. Menambahkan "pendengar" ke kotak pencarian tfSearch
//    Kode di dalamnya akan dijalankan setiap kali kita mengetik
tfSearch.addKeyListener(new java.awt.event.KeyAdapter() {
    @Override
    public void keyReleased(java.awt.event.KeyEvent evt) {
        String text = tfSearch.getText();
        // (?i) di depan teks berarti pencarian tidak memperdulikan huruf besar/kecil
        if (text.trim().length() == 0) {
            sorter.setRowFilter(null);
        } else {
            sorter.setRowFilter(RowFilter.regexFilter("(?i)" + text));
        }
    }
});

// ===== KODE BARU UNTUK FITUR PENCARIAN (SELESAI) =====

        //koneksi button Tambah Data ke Frame Tambah Tamu
        btnTambahData.addActionListener((java.awt.event.ActionEvent evt) -> {
            new TambahTamuFrame(tamu).setVisible(true);
            this.dispose();
        });

    }
    public void loadTableData() {
        try {
            // Kosongkan isi tabel
            tamu.setRowCount(0);

            // Query database
            Connection conn = DatabaseConn.connectDB();
            String query = "SELECT * FROM tamu";
            try (Statement stmt = conn.createStatement();
                 ResultSet rs = stmt.executeQuery(query)) {

                while (rs.next()) {
                    String nama = rs.getString("nama");
                    String nopol = rs.getString("nopol");
                    String tujuan = rs.getString("tujuan");
                    Date tanggal = rs.getDate("tanggal");
                    Time waktuDatang = rs.getTime("waktu_datang");
                    int durasi = rs.getInt("durasi");
                    String status = rs.getString("status");

                    Object[] rowData = {
                        nama,
                        nopol,
                        tujuan,
                        tanggal,
                        waktuDatang.toLocalTime().toString(),
                        durasi,
                        status
                    };
                    tamu.addRow(rowData);
                }
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this,
                "Gagal memuat data tabel: " + ex.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnTambahData = new javax.swing.JButton();
        btnFotoKTP = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableDataTamu = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        tfSearch = new javax.swing.JTextField();
        btnExport = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(98, 150, 232));
        jPanel1.setToolTipText("");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("List Data Tamu");

        btnTambahData.setForeground(new java.awt.Color(98, 150, 232));
        btnTambahData.setText("Tambah Data Tamu");

        btnFotoKTP.setForeground(new java.awt.Color(98, 150, 232));
        btnFotoKTP.setText("Ambil Foto KTP");
        btnFotoKTP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFotoKTPActionPerformed(evt);
            }
        });

        tableDataTamu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nama Tamu", "No.Polisi Kendaraan", "Tujuan Tamu", "Waktu Kedatangan", "Durasi Menetap"
            }
        ));
        jScrollPane1.setViewportView(tableDataTamu);

        jButton1.setText("Refresh");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Cari Tamu");

        btnExport.setText("Export ke CSV");
        btnExport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63)
                        .addComponent(tfSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addGap(41, 41, 41)
                        .addComponent(jButton1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnTambahData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnFotoKTP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnExport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(tfSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(25, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnTambahData, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnFotoKTP, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnExport, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(92, 92, 92))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFotoKTPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFotoKTPActionPerformed
        new FotoKTP().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnFotoKTPActionPerformed
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        loadTableData();  // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnExportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportActionPerformed
        // 1. Membuka dialog untuk memilih lokasi penyimpanan file
JFileChooser fileChooser = new JFileChooser();
fileChooser.setDialogTitle("Simpan Laporan sebagai CSV");
// Filter agar hanya menampilkan opsi .csv
fileChooser.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter("CSV File (*.csv)", "csv"));

int userSelection = fileChooser.showSaveDialog(this);

if (userSelection == JFileChooser.APPROVE_OPTION) {
    File fileToSave = fileChooser.getSelectedFile();
    // Memastikan file yang disimpan memiliki ekstensi .csv
    if (!fileToSave.getAbsolutePath().endsWith(".csv")) {
        fileToSave = new File(fileToSave.getAbsolutePath() + ".csv");
    }

    // 2. Proses menulis data ke dalam file CSV
    try (FileWriter csvWriter = new FileWriter(fileToSave)) {
        // Menulis baris header (judul kolom)
        csvWriter.append("ID,Nama Tamu,NOPOL Kendaraan,Tujuan,Tanggal,Waktu Kedatangan,Durasi (Menit)\n");

        // 3. Mengambil semua data dari database
        Connection conn = DatabaseConn.connectDB();
        String query = "SELECT * FROM tamu";
        try (Statement stmt = conn.createStatement();
             ResultSet rs = stmt.executeQuery(query)) {

            // 4. Menulis setiap baris data tamu ke file
            while (rs.next()) {
                csvWriter.append(rs.getString("id_tamu"));
                csvWriter.append(",");
                csvWriter.append(rs.getString("nama"));
                csvWriter.append(",");
                csvWriter.append(rs.getString("nopol"));
                csvWriter.append(",");
                csvWriter.append(rs.getString("tujuan"));
                csvWriter.append(",");
                csvWriter.append(rs.getDate("tanggal").toString());
                csvWriter.append(",");
                csvWriter.append(rs.getTime("waktu_datang").toString());
                csvWriter.append(",");
                csvWriter.append(String.valueOf(rs.getInt("durasi")));
                csvWriter.append("\n");
            }
        }

        csvWriter.flush(); // Memastikan semua data tertulis
        JOptionPane.showMessageDialog(this, "Data berhasil diekspor ke:\n" + fileToSave.getAbsolutePath(), "Ekspor Berhasil", JOptionPane.INFORMATION_MESSAGE);

    } catch (IOException | SQLException e) {
        JOptionPane.showMessageDialog(this, "Gagal mengekspor data: " + e.getMessage(), "Error Ekspor", JOptionPane.ERROR_MESSAGE);
    }
}// TODO add your handling code here:
    }//GEN-LAST:event_btnExportActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MainFrame().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExport;
    private javax.swing.JButton btnFotoKTP;
    private javax.swing.JButton btnTambahData;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableDataTamu;
    private javax.swing.JTextField tfSearch;
    // End of variables declaration//GEN-END:variables
}
