/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package LaporSatpam;
import java.awt.*;
import java.awt.image.BufferedImage;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;


/**
 *
 * @author LENOVO
 */
public class PreviewFoto extends javax.swing.JFrame {
    private BufferedImage capturedImage;
    private String nama;
    private String blok;
    private Runnable onSave;

    /**
     * Creates new form PreviewFoto
     */
    public PreviewFoto(BufferedImage image, String nama, String blok, Runnable onSave) {
        initComponents();
        this.capturedImage = image;
        this.nama = nama;
        this.blok = blok;
        this.onSave = onSave;
        
        JLabel label = new JLabel(new ImageIcon(image));
        PhotoReview.setLayout(new BorderLayout());
        PhotoReview.add(label, BorderLayout.CENTER);
        PhotoReview.revalidate();
        PhotoReview.repaint();

        LabelQuestion.setText("Yakin simpan foto untuk " + nama + " (" + blok + ")?");

        ButtonSimpan.addActionListener(e -> {
            System.out.println("Button Simpan diklik");
            if (onSave != null) {
                onSave.run();
            } else {
                JOptionPane.showMessageDialog(this, "onSave tidak diset!");
            }
            this.dispose();
        });

        ButtonRetake.addActionListener(e -> {
            new FotoKTP().setVisible(true);
            this.dispose();
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        ButtonSimpan = new javax.swing.JButton();
        ButtonRetake = new javax.swing.JButton();
        LabelQuestion = new javax.swing.JLabel();
        PhotoReview = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Background.setBackground(new java.awt.Color(98, 150, 232));

        ButtonSimpan.setText("Simpan Gambar");
        ButtonSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSimpanActionPerformed(evt);
            }
        });

        ButtonRetake.setText("Ambil Ulang Gambar");
        ButtonRetake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonRetakeActionPerformed(evt);
            }
        });

        LabelQuestion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LabelQuestion.setText("Apa Kamu Yakin Ingin Menyimpan Gambar ?");

        PhotoReview.setPreferredSize(new java.awt.Dimension(640, 480));

        javax.swing.GroupLayout PhotoReviewLayout = new javax.swing.GroupLayout(PhotoReview);
        PhotoReview.setLayout(PhotoReviewLayout);
        PhotoReviewLayout.setHorizontalGroup(
            PhotoReviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        PhotoReviewLayout.setVerticalGroup(
            PhotoReviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout BackgroundLayout = new javax.swing.GroupLayout(Background);
        Background.setLayout(BackgroundLayout);
        BackgroundLayout.setHorizontalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addContainerGap(143, Short.MAX_VALUE)
                .addComponent(ButtonSimpan)
                .addGap(125, 125, 125)
                .addComponent(ButtonRetake)
                .addGap(140, 140, 140))
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PhotoReview, javax.swing.GroupLayout.DEFAULT_SIZE, 654, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addGap(189, 189, 189)
                .addComponent(LabelQuestion)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        BackgroundLayout.setVerticalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelQuestion)
                .addGap(12, 12, 12)
                .addComponent(PhotoReview, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ButtonRetake, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonSimpan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSimpanActionPerformed

    }//GEN-LAST:event_ButtonSimpanActionPerformed

    private void ButtonRetakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonRetakeActionPerformed

    }//GEN-LAST:event_ButtonRetakeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PreviewFoto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PreviewFoto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PreviewFoto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PreviewFoto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JButton ButtonRetake;
    private javax.swing.JButton ButtonSimpan;
    private javax.swing.JLabel LabelQuestion;
    private javax.swing.JPanel PhotoReview;
    // End of variables declaration//GEN-END:variables
}
