/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package LaporSatpam;

import ConnectionDB.DatabaseConn;
import static ConnectionDB.DatabaseConn.conn;
import javax.swing.*;
import java.awt.event.*;
import LaporSatpam.HitungMundur;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Time;
import javax.swing.table.DefaultTableModel;
import java.time.LocalTime;


/**
 *
 * @author USER
 */
public class TambahTamuFrame extends javax.swing.JFrame {
    private DefaultTableModel tableModel;

    /**
     * Creates new form TambahTamuFrame
     */
    public TambahTamuFrame(String nama) {
        initComponents();
        DatabaseConn.connectDB();
        tfNamaTamu.setText(nama);
    }
    
    public TambahTamuFrame(){
        initComponents();
        DatabaseConn.connectDB();
    }
    
    public TambahTamuFrame(DefaultTableModel tamu) {
        initComponents();
        this.tableModel = tamu;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelMain = new javax.swing.JLabel();
        labelNama = new javax.swing.JLabel();
        tfNamaTamu = new javax.swing.JTextField();
        labelNopolTamu = new javax.swing.JLabel();
        tfNopolTamu = new javax.swing.JTextField();
        labelTujuanTamu = new javax.swing.JLabel();
        tfTujuanTamu = new javax.swing.JTextField();
        labelDurasiTamu = new javax.swing.JLabel();
        spinnerDurasi = new javax.swing.JSpinner();
        btnSimpan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(98, 150, 232));

        labelMain.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelMain.setForeground(new java.awt.Color(255, 255, 255));
        labelMain.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelMain.setText("Tambah Data Tamu");

        labelNama.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelNama.setForeground(new java.awt.Color(255, 255, 255));
        labelNama.setText("Nama Tamu");

        tfNamaTamu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNamaTamuActionPerformed(evt);
            }
        });

        labelNopolTamu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelNopolTamu.setForeground(new java.awt.Color(255, 255, 255));
        labelNopolTamu.setText("No.Polisi Kendaraan");

        labelTujuanTamu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelTujuanTamu.setForeground(new java.awt.Color(255, 255, 255));
        labelTujuanTamu.setText("Tujuan Tamu");

        labelDurasiTamu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelDurasiTamu.setForeground(new java.awt.Color(255, 255, 255));
        labelDurasiTamu.setText("Durasi Menetap Tamu");

        btnSimpan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSimpan.setForeground(new java.awt.Color(98, 150, 232));
        btnSimpan.setText("Simpan Data");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelNama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfNamaTamu)
                    .addComponent(labelNopolTamu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfNopolTamu)
                    .addComponent(labelTujuanTamu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfTujuanTamu)
                    .addComponent(labelDurasiTamu, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                    .addComponent(spinnerDurasi)
                    .addComponent(btnSimpan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelMain, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelNama)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfNamaTamu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelNopolTamu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfNopolTamu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelTujuanTamu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfTujuanTamu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelDurasiTamu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(spinnerDurasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(110, 110, 110)
                .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
    String nama = tfNamaTamu.getText();
    String nopol = tfNopolTamu.getText();
    String tujuan = tfTujuanTamu.getText();
    int durasi = (Integer) spinnerDurasi.getValue();

    LocalTime now = LocalTime.now().withNano(0); 
    java.sql.Time waktuDatang = java.sql.Time.valueOf(now);
    java.sql.Date tanggal = new java.sql.Date(System.currentTimeMillis());

    if (nama.isEmpty() || nopol.isEmpty() || tujuan.isEmpty()) {
        JOptionPane.showMessageDialog(this,
            "Tolong Isi Semua Data!",
            "Data Belum Terisi!",
            JOptionPane.ERROR_MESSAGE);
        return; 
    }

    try {
        String sql = "INSERT INTO tamu (nama, nopol, tujuan, waktu_datang, durasi, tanggal, status) VALUES (?, ?, ?, ?, ?, ?, ?)";
        PreparedStatement stmt = conn.prepareStatement(sql);
        stmt.setString(1, nama);
        stmt.setString(2, nopol);
        stmt.setString(3, tujuan);
        stmt.setTime(4, waktuDatang); 
        stmt.setInt(5, durasi);
        stmt.setDate(6, tanggal); // Set the current date
        stmt.setString(7, "menunggu"); // Initial status

        int rowsInserted = stmt.executeUpdate();
        if (rowsInserted > 0) {
            JOptionPane.showMessageDialog(this,
                "Data tamu berhasil ditambahkan ke database.",
                "Sukses",
                JOptionPane.INFORMATION_MESSAGE);
            
            HitungMundur.mulaiCountdown(nama, nopol, durasi);

            // Open MainFrame and refresh data
            MainFrame mainFrame = new MainFrame();
            mainFrame.loadTableData(); // Load the latest data
            mainFrame.setVisible(true); // Show the main frame
            dispose(); // Close the current frame
        }
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this,
            "Terjadi kesalahan saat menyimpan ke database: " + ex.getMessage(),
            "Error",
            JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void tfNamaTamuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNamaTamuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNamaTamuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TambahTamuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TambahTamuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TambahTamuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TambahTamuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TambahTamuFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSimpan;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelDurasiTamu;
    private javax.swing.JLabel labelMain;
    private javax.swing.JLabel labelNama;
    private javax.swing.JLabel labelNopolTamu;
    private javax.swing.JLabel labelTujuanTamu;
    private javax.swing.JSpinner spinnerDurasi;
    private javax.swing.JTextField tfNamaTamu;
    private javax.swing.JTextField tfNopolTamu;
    private javax.swing.JTextField tfTujuanTamu;
    // End of variables declaration//GEN-END:variables
}
